[package]
name = "easydb"
version = "0.0.1"
authors = ["liming <liming@admaster.com.cn>"]

[dependencies]
rustc-serialize = "0.3"
regex = "0.2"
postgres = "0.13"
rand = "0.3"
log = "0.3"

easy_util = {git = "https://limitee:20131988lm@github.com/limitee/easy_util.git"}


